# Generated by Django 5.0.3 on 2024-03-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(max_length=50)),
                ('sname', models.CharField(max_length=50)),
                ('marks', models.IntegerField()),
            ],
        ),
    ]
