# Generated by Django 5.0.3 on 2024-03-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_db',
            name='marks',
            field=models.IntegerField(),
        ),
    ]
